[Jan 2023 rotation] New scriptworker ed25519 key
mozilla-releng/scriptworker pull request #583
Opened 2023-01-26 23:18 UTC by hneiva

2023-01-26 23:25 UTC, gabrielBusta approved these changes

2023-01-26 23:50 UTC, gabrielBusta requested changes
Need to dig into those test failures

2023-01-27 15:38 UTC, ahal commented
Odd, the commit I made for this last time was pretty much identical: https://github.com/mozilla-releng/scriptworker/commit/27f58ba128a004ebe268c7b6b9c11dffb34a0de8 (other than black formatting)

2023-01-27 17:12 UTC, gabrielBusta commented
How odd...

2023-01-27 18:35 UTC, ahal commented
Looks like this is a Python change:
https://github.com/python/cpython/commit/1d4d677d1c90fcf4886ded0bf04b8f9d5b60b909

Changing the method to `assert_called_once_with` should fix it.

2023-01-27 18:39 UTC, ahal commented
I filed https://github.com/mozilla-releng/scriptworker/issues/584 to make the CI more reproducible.

2023-01-27 19:55 UTC, hneiva commented on tests/test_utils.py
> +    with mock.patch.object(utils, "createTemporaryCredentials") as patched:
renamed `p` to `patched` as it conflicts with pdb `p` command; took me longer than I'd like to admit to realize this is why I had issues debugging it 🥲

2023-01-27 20:08 UTC, ahal approved these changes

2023-01-27 20:48 UTC, gabrielBusta approved these changes

2023-01-27 20:50 UTC, merged